# Generated by Django 5.0 on 2023-12-16 23:07

import render.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('render', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(null=True, verbose_name=render.models.Categories),
        ),
    ]
